const fieldRules = Object.freeze({
    REQUIRED: 'REQUIRED',
    VALID_EMAIL: 'VALID_EMAIL',
    VALID_POSTAL_CODE: 'VALID_POSTAL_CODE',
    PASSWORD_CONFIRMATION_MATCHES_PASSWORD:
        'PASSWORD_CONFIRMATION_MATCHES_PASSWORD',
});

export default fieldRules;
